name: portflow
version: "1.0.0"
config-version: 2

profile: portflow

model-paths: ["models"]
test-paths: ["tests"]

models:
  portflow:
    staging:
      +materialized: view
    marts:
      +materialized: table
